spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/offer_harvester
  application:
    name: resume
server:
  servlet:
    context-path: /api/v1

eureka:
  client:
    server-url:
      default-zone:
        - http://localhost:8761/eureka
        - http://localhost:8762/eureka
        - http://loclahost:8763/eureka
---
spring:
  config:
    activate:
      on-profile: instance-1
server:
  port: 9000

---
spring:
  config:
    activate:
      on-profile: instance-2
server:
  port: 9001